Show process's last output in error message when service exits quickly (#69)
The `pebble logs` command can now see the logs of previously
stopped/terminated services
(see https://github.com/canonical/pebble/issues/57). But it's also useful to
include the last output (log lines) in the common "exited quickly" case, so
this change adds that output to the task log of the change.

This output will appear in the exception string automatically in charms, via
Python Operator Framework change
https://github.com/canonical/operator/pull/653.

The output (from `pebble start` trying to start a service with command `sleep
x`) appears as follows:

```
$ pebble start sleepx
error: cannot perform the following tasks:
- Start service "sleepx" (service exited too quickly with code 1)
```

And then if you view the task's log using `pebble tasks` (with the change ID
from `pebble changes`):

```
$ pebble tasks 1385
Status  Spawn                Ready                Summary
Error   today at 14:08 NZDT  today at 14:08 NZDT  Start service "sleepx"

......................................................................
Start service "sleepx"

2021-10-20T14:08:07+13:00 INFO Most recent service output:
    sleep: invalid time interval ‘x’
    Try 'sleep --help' for more information.
2021-10-20T14:08:07+13:00 ERROR service exited too quickly with code 1
```

Note that in the ring buffer the log lines are prefixed with
`2021-09-21T00:33:20.605Z [sleepx] `, so we strip that off here to avoid
double timestamps and make it look nicer for the user.