feat: add pebble check command (#574)
This PR adds a new "pebble check" command, which takes a single check
name as a required positional argument and returns the status of the
check synchronously.

This new subcommand is needed for the upcoming `pebble check <check>
--refresh` feature where a check will run immediately. See
[OP055](https://docs.google.com/document/d/1fDfb8FL9urUWhcvExYEWUXDTUq--a22V-v0GaRuLyFk/edit?tab=t.0)
(internal link) for more details. Changes:

- Reuse existing `/v1/checks` API endpoint. A new endpoint will be added
for the `--refresh` feature in a separate PR.
- Docs and unit tests are updated.
- Note: The `level` argument/filter from `pebble checks` (plural) is not
copied to this new subcommand because this command only gets a single
check by name, so the "filter by level" feature probably is not needed,
return the check by name in any case.

Some manual tests:

```bash
$ pebble check
error: the required argument `<check>` was not provided

$ pebble check chk1 chk2
error: too many arguments for command

$ ./pebble check chk1
No matching health checks.

$ ./pebble check check1
name: check1
level: ""
startup: enabled
status: up
failures: 0
threshold: 3
changeid: "1"
```