fix: command manager connect go routine leak (#869)
This is a port of a downstream project's fix to the command manager
connection handling logic. Previous to this fix, the connect method
could leak a go routine if the `execution` was found, but the connect
request was cancelled. The fix is to make the channel, which is sent
on without a select, a buffered channel of one.

This change also adds a regression test for the go routine leak.

Here is the test failure demonstrating the go routine leak.
```
$ GOEXPERIMENT=goroutineleakprofile go test -c ./internals/overlord/cmdstate
$ stress -fast -p 256 -count 1024 ./cmdstate.test

/tmp/nix-shell.L1vRQa/go-stress-20260529T151421-3792207636
OK: 1 passed
--- FAIL: Test (0.01s)
    goroutine 12 [chan send (leaked)]:
    github.com/canonical/pebble/internals/overlord/cmdstate.(*CommandManager).Connect.func2()
    	/home/hpidcock/work/pebble/internals/overlord/cmdstate/manager.go:77 +0x49
    created by github.com/canonical/pebble/internals/overlord/cmdstate.(*CommandManager).Connect in goroutine 11
    	/home/hpidcock/work/pebble/internals/overlord/cmdstate/manager.go:72 +0x148
FAIL
```